### ISSUE TITLE
Could you be more specific on what do after webpack -p

### ISSUE THREAD

**Issue by lmuzquiz** [xdvarpunen/webpackboot#1]
So what does ii .\public\index.html mean?

Does this run on localhost:8080/index.html or what?

**Comment by xdvarpunen** [comment]
@lmuzquiz It's powershell command and opens file with appropriate application. I just used it for "lazy way of opening website in browser".

**Comment by xdvarpunen** [comment]
@lmuzquiz README.md example is now commandline independent:
```shell
npm install # Install nodejs dependencies
webpack -p
# Open `\public\index.html`-file in browser and watch the result.
```
